-- DDL
CREATE TABLE EMP(  
  EMPNO    NUMBER(4,0),  
  ENAME    VARCHAR2(10),  
  JOB      VARCHAR2(9),  
  MGR      NUMBER(4,0),  
  HIREDATE DATE,  
  SAL      NUMBER(7,2),  
  COMM     NUMBER(7,2),  
  DEPTNO   NUMBER(2,0),  
  CONSTRAINT PK_EMP PRIMARY KEY (EMPNO),  
  CONSTRAINT FK_DEPTNO FOREIGN KEY (DEPTNO) REFERENCES DEPT (DEPTNO)  
);

CREATE INDEX EMP.EMP_DEPTNO_INDX1 ON EMP(DEPTNO);
GRANT SELECT ON EMP TO HR;

-- DML
INSERT INTO EMP (EMPNO, ENAME, JOB, HIREDATE, SAL, DEPTNO)
VALUES( 7839, 'KING', 'PRESIDENT', TO_DATE('17-11-1981','DD-MM-YYYY'), 5000, 10);

-- PL/SQL
DECLARE
   V_EMPNO NUMBER;
BEGIN
   SELECT EMPNO INTO V_EMPNO FROM EMP WHERE ENAME = 'KING');
   DBMS_OUTPUT.PUT_LINE(V_EMPNO);
END;
/

-- SELECT
SELECT D.DEPARTMENT_NAME,
       E.EMPLOYEE_NAME
FROM   DEPARTMENTS D
JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE  D.DEPARTMENT_ID >= 30
ORDER BY D.DEPARTMENT_NAME;

SELECT D.DEPARTMENT_NAME,
       E.EMPLOYEE_NAME     
FROM   DEPARTMENTS D
LEFT OUTER JOIN EMPLOYEES E ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
WHERE  D.DEPARTMENT_ID >= 30
ORDER BY D.DEPARTMENT_NAME, E.EMPLOYEE_NAME;
